version: "3.9"

services:
  pfs_server:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: pfs_server
    image: pfs_server
    env_file:
      - .env
    command: |
      sh -c "python manage.py test controller && (gunicorn -b 0.0.0.0:${PUBLIC_API_PORT} pfs.wsgi:application & python main.py)"
    ports:
      - "${PUBLIC_API_PORT}:${PUBLIC_API_PORT}"
      - "${PUBLIC_PROXY_PORT}:${PUBLIC_PROXY_PORT}"