version: "3.9"

services:
  pfs_service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: pfs_service
    image: pfs_service
    env_file:
      - .env
    command: |
      sh -c "pytest ./app/tests.py && (gunicorn -b 0.0.0.0:${PUBLIC_API_PORT} app:app & python ./app/server/ProxyForwarderServer.py)"
    ports:
      - "${PUBLIC_API_PORT}:${PUBLIC_API_PORT}"
      - "${PUBLIC_PROXY_PORT}:${PUBLIC_PROXY_PORT}"